### ISSUE TITLE
Add additional info into Plugin 

### ISSUE THREAD

**Issue by imanushin** [Excel-DNA/ExcelDna#142]
Sometimes plugin is marked as Disabled, so Excel-DNA is unable to register it (because it is already registered). This text should be added to the following line - https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.Integration/ExcelComAddIn.cs#L169

Sometimes the following error is appeared:
```
ComAddIn [Error] The Ribbon/COM add-in helper required by add-in **** could not be registered.
This is an unexpected error.
Error details: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at ExcelDna.Integration.ExcelComAddInHelper.LoadComAddIn(ExcelComAddIn addIn) : TargetInvocationException - Exception has been thrown by the target of an invocation.
```

Right workaround - open Disabled items in the Add-Ins tabs and re-enable target plugin.

Investigation is here - <http://seotoolsforexcel.com/com-add-in-helper-could-not-be-registered/>

**Comment by govert** [comment]
@imanushin  I've added this extra message in the error pop-up. I've updated the source, and pushed to NuGet as ExcelDna.AddIn version 0.35.1-beta2. I'm still tracking the idea of checking and cleaning up the Disabled Items before we attempt to load the ribbon, under issue https://github.com/Excel-DNA/ExcelDna/issues/141 .
