### ISSUE TITLE
ExcelDnaUtil.Application throws COMException

### ISSUE THREAD

**Issue by Mad-Lynx** [Excel-DNA/ExcelDna#171]
Spec: Excel 2016, Win10.

Description
--
When you run `ExcelDnaUtil.Application` **not from** MainThread, we will get null or object (depending if the file is open in Excel or not).
But when I opened file download from internet I got COMException.
The Excel is in "Protected view" mode:
![image](https://user-images.githubusercontent.com/21129562/38028636-6a634b12-328b-11e8-8bde-5c59bc439c7f.png)
And the file has this attribute:
![image](https://user-images.githubusercontent.com/21129562/38028734-af30208a-328b-11e8-95a7-8758a4e432e5.png)

Surprisingly this exception would not be thrown if I call `ExcelDnaUtil.Application` **from** MainThread.
In this case, everything works fine...

Repro-Steps
--
1) Download file from "untasted source" to have  "blocked flag"
2) Open this file in Excel
3) try to get `ExcelDnaUtil.Application` from MainThread - this will work
4) try to get `ExcelDnaUtil.Application` from any other thread - 💥 

Name | Value 
-- | --
Type | System.Runtime.InteropServices.COMException
ErrorCode | -2147352570 (0x80020006)
Message | "Unknown name. (Exception from HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))"
StackTrace | 
``` 
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at ExcelDna.Integration.ExcelDnaUtil.GetApplicationFromWindow(IntPtr hWndMain)
   at ExcelDna.Integration.ExcelDnaUtil.<>c__DisplayClass32_0.<GetApplicationFromWindows15>b__0(IntPtr hWndEnum, IntPtr param)
   at ExcelDna.Integration.ExcelDnaUtil.EnumThreadWindows(UInt32 dwThreadId, EnumThreadWindowsCallback callback, IntPtr param)
   at ExcelDna.Integration.ExcelDnaUtil.GetApplicationFromWindows15()
   at ExcelDna.Integration.ExcelDnaUtil.GetApplicationFromWindows()
   at ExcelDna.Integration.ExcelDnaUtil.get_Application()
   at MyApp.IsExcelAvailable() in C:\Repos\MyApp\MyFile.cs:line 90
```

**Comment by govert** [comment]
@Mad-Lynx I'll look at this bug - it's supposed to work. But since implementing this I've come to realize that it is a bad idea to use the COM interfaces from another thread and I now suggest that one _never_ does that. I keep this support to get the Application from another thread in `ExcelDnaUtil.Application` for now for compatibility, but if I had to implement it today I would not support that scenario at all.

**Comment by govert** [comment]
Possibly related to this discussion: https://groups.google.com/forum/#!searchin/exceldna/%22protected$20view%22%7Csort:date/exceldna/_NHOu-DEViU/PYMrZGhfBQAJ

**Comment by Mad-Lynx** [comment]
@govert yes, you are right. I have v0.33.9 and while I was make sure that the other issue (#170) is still happen in new version I didn't check this one 😞 

After upgrading to v0.34.6 the `ExcelDnaUtil.Application` will return object from the "Protected View".

Although, there are problem with `QueueAsMacro` in this case, and every 0.25s there are COMException flying from `Run`.
(I can describe it more here or create new ticket, as this is not really related to this topic anymore 😉 )

**Comment by govert** [comment]
@Mad-Lynx If there is an issue in the current version, different from #170, please open another ticket and close this one.
