### ISSUE TITLE
Skip abstract classes when creating instances of classes that implement `IExcelAddIn`

### ISSUE THREAD

**Issue by caioproiete** [Excel-DNA/ExcelDna#214]
Our current implementation attempts to create instances of classes that implement the `IExcelAddIn` interface, without checking if the class is ` abstract` and because of that, it throws an exception:

```
Initialization [Warning] GetExcelAddIns CreateInstance problem for type: MyNamespace.ExcelDnaAddIn - exception: System.MissingMethodException: Cannot create an abstract class.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at ExcelDna.Integration.AssemblyLoader.GetExcelAddIns(ExportedAssembly assembly, Type t, Boolean loadRibbons, List`1 addIns)
```

To reproduce, just declare an abstract class that implements the `IExcelAddIn` interface:

```csharp
public abstract class MyExcelDnaAddIn : IExcelAddIn
{
    public void AutoOpen()
    {
    }

    public void AutoClose()
    {
    }
}
```

**Comment by caioproiete** [comment]
This also affects interfaces that implement `IExcelAddIn` - we're attempt to instantiate interfaces as well, and obviously fail...

```
Initialization [Warning] GetExcelAddIns CreateInstance problem for type: MyNamespace.IMyAddInInterface - exception: System.MissingMethodException: Cannot create an instance of an interface.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at ExcelDna.Integration.AssemblyLoader.GetExcelAddIns(ExportedAssembly assembly, Type t, Boolean loadRibbons, List`1 addIns)

```

```csharp
public interface IMyExcelDnaAddIn : IExcelAddIn
{
    // ...
}
```
