### ISSUE TITLE
Ribbon/Com-Addin helper could not be registered

### ISSUE THREAD

**Issue by SathishRaju** [Excel-DNA/ExcelDna#220]
Recently i started getting this error when i debug the addin from Visual Studio. I also upgraded to the recent beta.4 version to see if it is helping. But it did not help. 

ComAddIn [Error] The Ribbon/COM add-in helper required by add-in Kloud2 Add-In could not be registered.
This may be due to the helper add-in being disabled by Excel.
To repair, open Disabled items in the Options->Add-Ins page and re-enable target add-in, then restart Excel.
Error details: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at ExcelDna.Integration.ExcelComAddInHelper.LoadComAddIn(ExcelComAddIn addIn) : TargetInvocationException - Exception has been thrown by the target of an invocation.

**Comment by govert** [comment]
@SathishRaju When debugging a ribbon add-in, if you terminate the debugging session and thus the Excel process during a ribbon callback, Excel will disable your add-in, thinking it is crashing Excel.

**Comment by andrewkittredge** [comment]
Instructions on how to fix.

https://knowledge.calcbench.com/hc/en-us/articles/115007936967-Security-warning-in-Excel-when-running-the-Calcbench-Add-in-or-The-Ribbon-COM-Add-in-helper-required-by-add-in-CalcbenchExcel-Add-In-could-not-be-registered-
