### ISSUE TITLE
ProgId/Guid for Custom Task Pane Helper

### ISSUE THREAD

**Issue by p0n3** [Excel-DNA/ExcelDna#373]
**Problem**
There is no easy way to set ProgId/Guid for a Custom Task Pane Helper component (`ExcelCustomTaskPaneAddIn`), which might cause a problem in restricted environments.

**Details**
`ExcelCustomTaskPaneAddIn` is an internal class and the instance is being created in the `GetCTPFactory` method inside `CustomTaskPaneFactory`:
```
// Register and create addin
_addin = new ExcelCustomTaskPaneAddIn { DnaLibrary = DnaLibrary.CurrentLibrary };
ExcelComAddInHelper.LoadComAddIn(_addin);
```
`LoadComAddIn` checks if the class has ProgId/Guid attribute, and if not it generates id based on the xll path. It works well if you e.g.  extend `ExcelRibbon` class, but `ExcelCustomTaskPaneAddIn` is an internal class, so you cannot do much with it, therefore it always uses generated id.

**Comment by govert** [comment]
That sounds reasonable. Do you mean you need to register the control and CTP add-in in the registry yourself, or at another time?

The ExcelCustomTaskPane code is quite small with two classes and mostly dealing with the on-demand COM registration.
So you could just make a copy of the code from https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.Integration/ExcelCustomTaskPane.cs in your own add-in project, and rename the types to `MyCustomTaskPaneFactory' and `MyCustomTaskPaneAddIn`. The only coupling I see with the rest of Excel-DNA is the fact that the add-in class derives from `ExcelAddIn`, so you need that. I might be missing something, but it seems worth a try.

**Comment by p0n3** [comment]
> Do you mean you need to register the control and CTP add-in in the registry yourself, or at another time?

I just need to have a fixed ProgId to be able to whitelist it in a whole organization.

 > you could just make a copy of the code

I tried, but the problem is there are bunch of internal classes/interfaces inside this file that cannot be accessed from another assembly like: `ICustomTaskPaneConsumer`, `ProgIdRegistration`, `ClsIdRegistration`, `SingletonClassFactoryRegistration` which uses another internal method  - `RegisterClassFactory` and so on and so on.

**Comment by govert** [comment]
OK - I see there is some more plumbing behind it, including the class factory provided by Excel-DNA.

**Comment by theboyknowsclass** [comment]
any word on this?

**Comment by Sergey-Vlasov** [comment]
To create a restricted environment, I enabled the "Block all unmanaged add-ins" policy:

<img width="763" height="417" alt="Image" src="https://github.com/user-attachments/assets/618dbeb2-532c-4be3-b8ab-a292a5b0678c" />


Now trying to load ExcelDna.Test\bin\Debug\net6.0-windows\ExcelDna.Test-AddIn.xll:

> ComAddIn [Error] The Ribbon/COM add-in helper required by add-in Test .NET 6 add-in could not be registered.
> This may be due to the helper add-in being disabled by Excel.
> To repair, open Disabled items in the Options->Add-Ins page and re-enable target add-in, then restart Excel.
> Error details: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Runtime.InteropServices.COMException (0x80004005): The add-in you have selected is disabled by your system administrator.
>    --- End of inner exception stack trace ---
>    at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
>    at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
>    at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args, CultureInfo culture)
>    at ExcelDna.Integration.ComInterop.TypeAdapter.SetProperty(String name, Object value, Object comObject) in e:\programming\Govert\Excel-DNA\ExcelDna-ProgId\Source\ExcelDna.Integration\ComInterop\TypeAdapter.cs:line 46
>    at ExcelDna.Integration.ExcelComAddInHelper.LoadComAddIn(ExcelComAddIn addIn) in e:\programming\Govert\Excel-DNA\ExcelDna-ProgId\Source\ExcelDna.Integration\ComInterop\ExcelComAddInHelper.cs:line 133 : TargetInvocationException - Exception has been thrown by the target of an invocation.

**Comment by Sergey-Vlasov** [comment]
To resolve the ribbon loading error, generate and add ProgId/Guid to Source\ExcelDna.Test\RibbonController.cs:

```cs
[ComVisible(true)]
[ProgId("175c15e3-4dd8-49d0-94cf-f95800017594")]
[Guid("6242439e-ecc6-46eb-a666-edd3d93414a4")]
public class RibbonController : ExcelRibbon
```

And add the ProgId to the List of managed add-ins:

<img width="1209" height="762" alt="Image" src="https://github.com/user-attachments/assets/60a61354-129a-4324-8cef-11f6c4d8bb14" />

**Comment by Sergey-Vlasov** [comment]
Sample code to create a custom task pane:

```cs
internal class CustomPane
{
    public static void Show()
    {
        var myControl = new MyUserControl();
        var customPane = CustomTaskPaneFactory.CreateCustomTaskPane(myControl, nameof(myControl));

        customPane.Visible = true;
    }
}

public interface IMyUserControl { }

[ComVisible(true)]
[Guid("c5a18d1b-b798-49cf-9a3f-37a094905170")]
[ComDefaultInterface(typeof(IMyUserControl))]
public class MyUserControl : UserControl, IMyUserControl { }
```

When CustomPane.Show() is called from a command:

> ComAddIn [Error] The Ribbon/COM add-in helper required by add-in Test .NET 6 add-in could not be registered.
> This may be due to the helper add-in being disabled by Excel.
> To repair, open Disabled items in the Options->Add-Ins page and re-enable target add-in, then restart Excel.
> Error details: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Runtime.InteropServices.COMException (0x80004005): The add-in you have selected is disabled by your system administrator.
>    --- End of inner exception stack trace ---
>    at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
>    at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
>    at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args, CultureInfo culture)
>    at ExcelDna.Integration.ComInterop.TypeAdapter.SetProperty(String name, Object value, Object comObject) in e:\programming\Govert\Excel-DNA\ExcelDna-ProgId\Source\ExcelDna.Integration\ComInterop\TypeAdapter.cs:line 46
>    at ExcelDna.Integration.ExcelComAddInHelper.LoadComAddIn(ExcelComAddIn addIn) in e:\programming\Govert\Excel-DNA\ExcelDna-ProgId\Source\ExcelDna.Integration\ComInterop\ExcelComAddInHelper.cs:line 133 : TargetInvocationException - Exception has been thrown by the target of an invocation.

**Comment by Sergey-Vlasov** [comment]
I've added stable ProgId/Guid for a Custom Task Pane Helper component (ExcelCustomTaskPaneAddIn).

To resolve the custom task pane creation error in a restricted environment, add ExcelDna.CustomTaskPaneAddIn to the List of managed add-ins:

<img width="496" height="336" alt="Image" src="https://github.com/user-attachments/assets/1a36f892-93b6-41f4-bb60-322121fc3e9d" />
