### ISSUE TITLE
System.Drawing.Common and LogDisplay load errors

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#566]
Under .NET 6 add-ins, the LogDisplay may fail to load with an error complaining about a set_Font method not found.
This relates to a newer version of the assembly System.Drawing.Common being present in the output directory.
There is a deep .NET 6 mess related to this file, and why it might be present after referencing some packages.
See for example https://github.com/dotnet/runtime/issues/64592

If using the System.Configuration.ConfigurationManager it might help to reference version 6.0.0 instead of 6.0.1.

Otherwise, the file can be explicitly deleted in the build:
```
<Target Name="RemoveSystemDrawingCommon" AfterTargets="ResolveAssemblyReferences">
  <ItemGroup>
    <ReferencePath Remove="@(ReferencePath)" Condition="%(ReferencePath.NuGetPackageId) == 'System.Drawing.Common'" />
  </ItemGroup>
</Target>
```

Is this safe? Presumably not always.

**Comment by nsulikowski** [comment]
I am getting this error, and I don't have a reference to System.Drawing.Common. Help!

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'Void System.Windows.Forms.Control.set_Font(System.Drawing.Font)'.
   at ExcelDna.Logging.LogDisplayForm.InitializeComponent()
   at ExcelDna.Logging.LogDisplayForm..ctor()
   at ExcelDna.Logging.LogDisplayForm.ShowForm()


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.CoreLib.dll
----------------------------------------
ExcelDna.ManagedHost
    Assembly Version: 1.1.0.0
    Win32 Version: 1.6.0.0
    CodeBase: file:///C:/Users/NESTOR~1/AppData/Local/Temp/ExcelDna.Host/16087b64-4309-491f-b4fe-0942a4324fc0/ExcelDna.ManagedHost.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.InteropServices.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Collections.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/Microsoft.Win32.Primitives.dll
----------------------------------------
ExcelDna.Loader
    Assembly Version: 1.1.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.CoreLib.dll
----------------------------------------
ExcelDna.Integration
    Assembly Version: 1.1.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.CoreLib.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Linq.Expressions.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Threading.Thread.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Threading.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1523.11702
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1523.11702
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/System.Drawing.Common.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1523.11702
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/Accessibility.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Xml.XmlSerializer.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.Xml.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Xml.ReaderWriter.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Memory.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.Uri.dll
----------------------------------------
IntersectXLL
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.CoreLib.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Text.RegularExpressions.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Collections.Concurrent.dll
----------------------------------------
IntersectCore
    Assembly Version: 1.0.46.0
    Win32 Version: 1.0.46
    CodeBase: file:///D:/Software/IntersectXLL/net6.0-windows/IntersectCore.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Threading.Tasks.Parallel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Threading.Tasks.Parallel.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Diagnostics.Tracing.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///D:/Software/IntersectXLL/net6.0-windows/System.Drawing.Common.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Linq.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Reflection.Primitives.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.CoreLib.dll
----------------------------------------
Ardalis.SmartEnum
    Assembly Version: 1.0.8.0
    Win32 Version: 1.0.8.0
    CodeBase: file:///D:/Software/IntersectXLL/net6.0-windows/Ardalis.SmartEnum.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/netstandard.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Diagnostics.Process.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Collections.NonGeneric.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Threading.ThreadPool.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Numerics.Vectors.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1523.11507
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Reflection.Metadata.dll
----------------------------------------

************** JIT Debugging **************


```

**Comment by nsulikowski** [comment]
If I delete `System.Drawing.Common.dll`, it reappears when I rebuild the project.
I see this dependency:
![image](https://user-images.githubusercontent.com/2067703/227316531-380522d5-090e-4219-a57b-8ba602e099e9.png)
I'm not sure why Microsoft.Windows.Compatibility is there, and/or why I may need it :-)

**Comment by govert** [comment]
It's expected that every build puts it back in the output directory.
My original entry above has an example of a target you can add to the project file to remove it after the build.

**Comment by nsulikowski** [comment]
Thanks for your quick response @govert.
I put the target in my project, and it doesn't delete the dll. 
If I delete it manually and run, I still get the error, even though System.Drawind.Common.dll doesn't exist:

![image](https://user-images.githubusercontent.com/2067703/227321383-3599913f-eaf7-4adc-96b5-5bc51518e550.png)

**Comment by govert** [comment]
OK - I now see the Target doesn't work for my test project either.

Does it make a difference if you add this property to the project:
```
<UseWindowsForms>true</UseWindowsForms>
```

It makes my output not have System.Drawing.Common.dll anymore.

**Comment by nsulikowski** [comment]
I already have `<UseWindowsForms>true</UseWindowsForms>` in my project.

**Comment by govert** [comment]
I don't know where the error comes from when you don't have System.Drawing.Common.dll in the output. I guess I still don't understand the problem right.

**Comment by nsulikowski** [comment]
Would it help if I try to install an older version of `System.Drawing.Common.dll` ?
If so, what version?

**Comment by govert** [comment]
From what I've seen, you must make it so that there is no System.Drawing.Common in the output. One culprit was System.Configuration.ConfigurationManager v 6.0.1 (or anything that pulls it in). 
You might want to start with a little project that works, and add packages to it one by one.

**Comment by nsulikowski** [comment]
Do you need `Microsoft.Windows.Compatibility` for the Logging window? That seems to be the nuget package that depends on `System.Drawind.Common.dll`.

**Comment by govert** [comment]
Excel-DNA does not need anything.

**Comment by govert** [comment]
(Beyond net6.0-windows) though it does target and load the 'Desktop' runtime.

**Comment by nsulikowski** [comment]
Good news. I removed the nuget package `Microsoft.Windows.Compatibility`, and now `System.Drawing.Common.dll` doesn't get copied to the output, and now it works.
Thanks for trying this with me.

**Comment by govert** [comment]
Yay!

**Comment by pfernie** [comment]
I ran into this as well; unfortunately, i was unable to remove the intermediate dependency that was introducing `System.Drawing.Common` (`NetMQ`, in my case). I found that while the Target in this (and the linked) issue didn't prevent the dll being copied into my output dir, the following did:
```
  <Target Name="RemoveSystemDrawingCommon" AfterTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="%(ReferenceCopyLocalPaths.NuGetPackageId) == 'System.Drawing.Common'" />
    </ItemGroup>
  </Target>
```

From my reading of the linked issue, this seems to be a valid fix, although this is as you say a bit of a .net mess.

**Comment by AntonZhernosek** [comment]
I've run into this issue today and just in case more people have it, here is what was happening 

I was working on a dotnet 7 project and there was an idea to reuse some of the logic within an Excel add-in. After making everything backwards-compatible with dotnet 6, I've run into this issue. This only showed up when trying to initialise Intellisense and not without it

The source of the problem was a Microsoft.Data.SqlClient dependency on Microsoft.Configuration.ConfigurationManager (as described above).
I've tinkered around with various solutions, but what ultimately helped is using System.Data.SqlClient for dotnet 6 build and Microsoft.Data.SqlClient for dotnet 7. The difference in the interface is very minor and other additions/fixes are not significant enough to warrant being needed by an Excel plugin. And there were only a few changes that had to be implemented for the downgrade to compile

Hope this helps someone aswell
