### ISSUE TITLE
Need StrongName  assembly

### ISSUE THREAD

**Issue by zwq00000** [Excel-DNA/ExcelDna#76]
```
ExcelDna.Integration Warning: 1 : Type RedRiver.Measuring.Commons.DataHelperCommands could not be processed. Error: System.IO.FileLoadException: 未能加载文件或程序集“ExcelDna.Integration, Version=0.33.5730.40390, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。需要强名称程序集。 (异常来自 HRESULT:0x80131044)
文件名:“ExcelDna.Integration, Version=0.33.5730.40390, Culture=neutral, PublicKeyToken=null”
   在 System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   在 System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   在 System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   在 System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   在 System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   在 System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   在 System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Boolean inherit)
   在 ExcelDna.Integration.AssemblyLoader.IsMethodMarkedForExport(MethodInfo mi)
   在 ExcelDna.Integration.AssemblyLoader.IsMethodSupported(MethodInfo mi, Boolean explicitExports)
   在 ExcelDna.Integration.AssemblyLoader.GetExcelMethods(Type t, Boolean explicitExports, List`1 excelMethods)
   在 ExcelDna.Integration.AssemblyLoader.ProcessAssemblies(List`1 assemblies, List`1 methods, List`1 addIns, List`1 rtdServerTypes, List`1 comClassTypes)
```

**Comment by govert** [comment]
See https://groups.google.com/d/topic/exceldna/SFvjgn_GINA/discussion

**Comment by zwq00000** [comment]
Thanks

**Comment by iamveritas** [comment]
I get a slightly different error with the version 1.5.0
My assembly is strongly named, I verified it with sn.exe tool. However I get the same error not matter if I sign or not the assembly. Any idea what is going on in my case?

ExcelDna.Integration Warning: 1 : Type MyType.Method could not be processed. Error: System.IO.FileLoadException: A strongly-named assembly is required. 
(Exception from HRESULT: 0x80131044)
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Boolean inherit)
   at ExcelDna.Integration.AssemblyLoader.IsMethodMarkedForExport(MethodInfo mi)
   at ExcelDna.Integration.AssemblyLoader.IsMethodSupported(MethodInfo mi, Boolean explicitExports)
   at ExcelDna.Integration.AssemblyLoader.GetExcelMethods(Type t, Boolean explicitExports, List`1 excelMethods)
   at ExcelDna.Integration.AssemblyLoader.ProcessAssemblies(List`1 assemblies, List`1 methods, List`1 addIns, List`1 rtdServerTypes, List`1 comClassTypes)

**Comment by augustoproiete** [comment]
@iamveritas Do you use any NuGet packages other than ExcelDna ones in your project? The assemblies in these packages also need to be strong-named.

**Comment by iamveritas** [comment]
no I am not. thanks for replying back.

**Comment by augustoproiete** [comment]
If you could put a sample project together that reproduces this error it might make it easier to spot what's causing this - post a link here when you have it

**Comment by iamveritas** [comment]
thanks for getting back on this. I was just playing around for my learning and I just dropped the idea to move forward. thank you again.
